server:
  port: 8092
  servlet:
    context-path: /redis

spring:
  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 5000   # 连接超时
    jedis:
      pool:
        type: jedisPool
        max-wait: 1000    # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-active: 2000  # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 300     # 连接池中的最大空闲连接
        min-idle: 0       # 连接池中的最小空闲连接