server:
  port: 8092

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/springboot-redis?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  redis:
    database: 3
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 5000   # 连接超时
    jedis:
      pool:
        type: jedisPool
        max-wait: 1000    # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-active: 2000  # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 300     # 连接池中的最大空闲连接
        min-idle: 0       # 连接池中的最小空闲连接